# Generated by Django 5.1.6 on 2026-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=64)),
                ('transaction_hash', models.CharField(max_length=200, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('issuer_address', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('revoked', 'Revoked')], default='stored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['certificate_id', 'status'], name='blockchain__certifi_5d00f6_idx')],
            },
        ),
    ]
