# Generated by Django 5.1.6 on 2026-03-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_ip', models.GenericIPAddressField()),
                ('verification_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('tampered', 'Tampered'), ('revoked', 'Revoked'), ('expired', 'Expired')], max_length=20)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='certificates.certificate')),
            ],
        ),
    ]
