# Generated by Django 5.1.6 on 2026-03-04 22:44

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=120, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='certificates.university')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=64, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=120)),
                ('university_name', models.CharField(max_length=255)),
                ('certificate_serial_number', models.CharField(max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField()),
                ('certificate_hash', models.CharField(db_index=True, max_length=64)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('pdf_file', models.FileField(upload_to='certificates/', validators=[certificates.models.validate_pdf])),
                ('ipfs_cid', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.university')),
            ],
            options={
                'indexes': [models.Index(fields=['certificate_id', 'status'], name='certificate_certifi_f5962c_idx')],
            },
        ),
    ]
