# Generated by Django 5.1.6 on 2026-03-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('needs_review', 'Needs Review'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='needs_review', max_length=20),
        ),
    ]
