# Generated by Django 5.1.6 on 2026-03-05 10:42

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_student_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='college_certificate_pdf',
            field=models.FileField(blank=True, upload_to='issued/college/', validators=[certificates.models.validate_pdf]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='combined_certificate_pdf',
            field=models.FileField(blank=True, upload_to='issued/combined/', validators=[certificates.models.validate_pdf]),
        ),
    ]
