# Generated by Django 5.1.6 on 2026-03-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_college_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('ocr_extracted', 'OCR Extracted'), ('auto_reprocess', 'Auto Reprocess'), ('approved', 'Approved'), ('anchored', 'Anchored On Blockchain'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('rejected', 'Rejected')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='certificates.certificate')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='certificate_event_t_2a6a9b_idx')],
            },
        ),
    ]
