# Generated by Django 5.1.6 on 2026-04-05 19:21

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_uploadjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='uploadjob',
            new_name='certificate_status_a95ecb_idx',
            old_name='certificate_uploadj_a05618_idx',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='college_certificate_pdf',
            field=models.FileField(blank=True, upload_to='issued/college/', validators=[certificates.models.validate_certificate_input]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='combined_certificate_pdf',
            field=models.FileField(blank=True, upload_to='issued/combined/', validators=[certificates.models.validate_certificate_input]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(upload_to='certificates/', validators=[certificates.models.validate_certificate_input]),
        ),
    ]
