# Generated by Django 5.1.6 on 2026-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='University Verification Portal', max_length=255)),
                ('college_address', models.TextField(blank=True)),
                ('verification_message', models.CharField(default='Certificate authenticity verified on blockchain', max_length=255)),
                ('primary_color', models.CharField(default='#1f6feb', max_length=7)),
                ('college_logo', models.ImageField(blank=True, upload_to='branding/')),
                ('college_banner', models.ImageField(blank=True, upload_to='branding/')),
                ('homepage_background', models.ImageField(blank=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
