# Generated by Django 5.1.6 on 2026-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingconfigmodel',
            name='college_name',
            field=models.CharField(default='VerifyCerts', max_length=255),
        ),
    ]
